### ISSUE TITLE
Unrecoverable Runtime NullPointerException exception thrown when socket connection cannot be established

### ISSUE THREAD

**Issue by damianflannery** [LeonNicholls/Anymote-for-Java#1]
Hey Leon,

I had an anymote connection open to my GTV box when it (GTV) lost connectivity causing the phone app to splode with the stack trace below. I traced to this portion of code in AnymoteSender:

/**
     \* Attempts to establish connection with the Anymote service socket.
     \* 
     \* @param sslSocket TV device socket.
     \* @return boolean indicating if connection to socket was successful.
     */
public boolean attemptToConnect(final SSLSocket sslSocket) {
        if (sslSocket == null) {
            throw new NullPointerException("null socket");
        }
        return instantiateProtocol(sslSocket);
    }

Should it return false here instead of throwing a Runtime exception or is there some other way to cleanly disconnect?

12-13 10:27:44.626: E/anymote(8172): ConnectingActivity: (IOE) Could not create socket to GTV device
12-13 10:27:44.626: E/anymote(8172): java.net.ConnectException: failed to connect to /192.168.1.18 (port 9551): connect failed: ECONNREFUSED (Connection refused)
12-13 10:27:44.626: E/anymote(8172):    at libcore.io.IoBridge.connect(IoBridge.java:114)
12-13 10:27:44.626: E/anymote(8172):    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
12-13 10:27:44.626: E/anymote(8172):    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
12-13 10:27:44.626: E/anymote(8172):    at java.net.Socket.startupSocket(Socket.java:566)
12-13 10:27:44.626: E/anymote(8172):    at java.net.Socket.tryAllAddresses(Socket.java:127)
12-13 10:27:44.626: E/anymote(8172):    at java.net.Socket.<init>(Socket.java:177)
12-13 10:27:44.626: E/anymote(8172):    at java.net.Socket.<init>(Socket.java:149)
12-13 10:27:44.626: E/anymote(8172):    at javax.net.ssl.SSLSocket.<init>(SSLSocket.java:55)
12-13 10:27:44.626: E/anymote(8172):    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.<init>(OpenSSLSocketImpl.java:119)
12-13 10:27:44.626: E/anymote(8172):    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:64)
12-13 10:27:44.626: E/anymote(8172):    at com.entertailion.java.anymote.connection.ConnectingTask.attemptToConnect(ConnectingTask.java:355)
12-13 10:27:44.626: E/anymote(8172):    at com.entertailion.java.anymote.connection.ConnectingTask.connect(ConnectingTask.java:198)
12-13 10:27:44.626: E/anymote(8172):    at com.entertailion.java.anymote.connection.ConnectingTask.run(ConnectingTask.java:175)
12-13 10:27:44.626: E/anymote(8172): Caused by: libcore.io.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
12-13 10:27:44.626: E/anymote(8172):    at libcore.io.Posix.connect(Native Method)
12-13 10:27:44.626: E/anymote(8172):    at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:85)
12-13 10:27:44.626: E/anymote(8172):    at libcore.io.IoBridge.connectErrno(IoBridge.java:127)
12-13 10:27:44.626: E/anymote(8172):    at libcore.io.IoBridge.connect(IoBridge.java:112)
12-13 10:27:44.626: E/anymote(8172):    ... 12 more
12-13 10:27:44.743: E/anymote(8172): ConnectingActivity: Failed to connect
12-13 10:27:44.743: E/anymote(8172): java.net.ConnectException: failed to connect to /192.168.1.18 (port 9552): connect failed: ECONNREFUSED (Connection refused)
12-13 10:27:44.743: E/anymote(8172):    at libcore.io.IoBridge.connect(IoBridge.java:114)
12-13 10:27:44.743: E/anymote(8172):    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
12-13 10:27:44.743: E/anymote(8172):    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
12-13 10:27:44.743: E/anymote(8172):    at java.net.Socket.startupSocket(Socket.java:566)
12-13 10:27:44.743: E/anymote(8172):    at java.net.Socket.tryAllAddresses(Socket.java:127)
12-13 10:27:44.743: E/anymote(8172):    at java.net.Socket.<init>(Socket.java:177)
12-13 10:27:44.743: E/anymote(8172):    at java.net.Socket.<init>(Socket.java:149)
12-13 10:27:44.743: E/anymote(8172):    at com.entertailion.java.anymote.connection.ConnectingTask.attemptToPair(ConnectingTask.java:255)
12-13 10:27:44.743: E/anymote(8172):    at com.entertailion.java.anymote.connection.ConnectingTask.connect(ConnectingTask.java:204)
12-13 10:27:44.743: E/anymote(8172):    at com.entertailion.java.anymote.connection.ConnectingTask.run(ConnectingTask.java:175)
12-13 10:27:44.743: E/anymote(8172): Caused by: libcore.io.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
12-13 10:27:44.743: E/anymote(8172):    at libcore.io.Posix.connect(Native Method)
12-13 10:27:44.743: E/anymote(8172):    at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:85)
12-13 10:27:44.743: E/anymote(8172):    at libcore.io.IoBridge.connectErrno(IoBridge.java:127)
12-13 10:27:44.743: E/anymote(8172):    at libcore.io.IoBridge.connect(IoBridge.java:112)
12-13 10:27:44.743: E/anymote(8172):    ... 9 more
12-13 10:27:44.743: E/ACRA(8172): ACRA caught a NullPointerException exception for com.dailyburn.challenge. Building report.
12-13 10:27:45.118: E/ACRA(8172): DailyBurn fatal error : null socket
12-13 10:27:45.118: E/ACRA(8172): java.lang.NullPointerException: null socket
12-13 10:27:45.118: E/ACRA(8172):   at com.entertailion.java.anymote.client.AnymoteSender.attemptToConnect(AnymoteSender.java:118)
12-13 10:27:45.118: E/ACRA(8172):   at com.entertailion.java.anymote.connection.ConnectingTask.run(ConnectingTask.java:176)
12-13 10:27:45.157: E/InputDispatcher(311): channel '41839498 com.dailyburn.challenge/com.dailyburn.challenge.LoginActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
12-13 10:27:45.196: E/jdwp(8803): Failed sending reply to debugger: Broken pipe
12-13 10:31:36.282: E/Process(311): Error getting pid for '0'

**Comment by LeonNicholls** [comment]
Please check that you have the latest version of the code from the Anymote-for-Java library. The line numbers in the stack trace don't match the checked in code.

**Comment by damianflannery** [comment]
Thanks. Looks like you already fixed the issue in that latest build.
